export const opcionesData = [
  { value: "name", label: "Nombre" },
  { value: "lastName", label: "Apellido" },
  { value: "ci", label: "Cedula" },
  { value: "ruc", label: "Ruc" },
  { value: "email", label: "correo" },
  { value: "telefono", label: "telefono" },
  { value: "direccion", label: "direccion" },
  { value: "ciudad", label: "ciudad" },
  { value: "estado", label: "estado" },
  { value: "pais", label: "pais" },
  { value: "codigoPostal", label: "codigoPostal" },
  { value: "fechaNacimiento", label: "fechaNacimiento" },
  { value: "genero", label: "genero" },
  { value: "numeroHijos", label: "numero de hijos" },
  { value: "estadoCivil", label: "estado civil" },
  { value: "ocupacion", label: "ocupacion" },
  { value: "nivelEstudios", label: "nivel de estudios" },
  { value: "ingresosMensuales", label: "ingresos mensuales" },
  { value: "tipoVivienda", label: "tipo de vivienda" },
  { value: "numeroVehiculos", label: "numero de vehiculos" },
];
